#!/usr/bin/with-contenv bash


UMASK_SET=${UMASK_SET:-022}

umask "$UMASK_SET"
export HOME=/media/dvr
echo "Running Channels DVR"
exec \
  s6-setuidgid channeluser /bin/bash -c \
  'cd /media/dvr/data && ../latest/channels-dvr >> channels-dvr.log 2>&1'
